import type {Metadata} from "next";
import {Geist, Geist_Mono, Funnel_Display} from "next/font/google";
import "./globals.css";
import {Header} from "@/components/shared/header";
import {Footer} from "@/components/shared/footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const funnelDisplay = Funnel_Display({
    variable: "--font-funnel",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} ${funnelDisplay.variable} antialiased`}
        >
        <Header/>
        <main>
            {children}
        </main>
        <Footer/>
        </body>
        </html>
    );
}
